apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: my-app
  template:
    metadata:
      labels:
        name: my-app
    spec:
      containers:
      - name: my-apps
        image: us-docker.pkg.dev/heroic-tide-348508/terra/test:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: my-app-cm
